### ISSUE TITLE
Frequent Crashes When Calculating or Filtering

### ISSUE THREAD

**Issue by Sat727** [tylercamp/palcalc#57]
Very impressive tool that's been extremely helpful when it works. However, I'm running into frequent issues when trying to run calculations and filter pals from a specific user. I am using an Xbox Game Pass Dedicated Server save.

I am running into 2 issues while using the tool.

# 1. I can't filter per player

I cannot select a specific user for their pals, this results in a crash if I try. Additionally my user is missing from the guild player list. It's hard to determine if my pals are being accounted for in the calculations since I cannot inspect, or view any further details in the GUI as it would result in a crash.

# 2. Frequent crashes when calculating.

It seems it has a 1/3 chance to crash when calculating breeds

I'll continue to look into this and I'll create a pull request if a solution is found.

[CRASHLOG.zip](https://github.com/user-attachments/files/17477661/CRASHLOG.zip)

Example 2 : 
[CRASHLOG.zip](https://github.com/user-attachments/files/17477918/CRASHLOG.zip)

**Comment by tylercamp** [comment]
@Sat727 Thanks for the CRASHLOG files, the save has some peculiar items:

1. Player "Your Daddy" isn't a member of any guild
2. The guilds "Unnamed Guild" and "Kittens" have a member with ID "f1a4f926", which doesn't match any of the players discovered in the save file
3. This "f1a4f926" player is a member of two guilds (I expect players will always be a member of exactly one guild) 

> I am using an Xbox Game Pass Dedicated Server save.

Does this mean an Xbox Game Pass save was converted for use in a dedicated server?

**Comment by Sat727** [comment]
Yes, the save was converted for use in a dedicated server. This could be the reason there are anomalies in the save file

**Comment by tylercamp** [comment]
@Sat727 Hopefully fixed with 14f5f099c5e3c5b7af73a2970aacda04062f0796, try [the 1.7.6-beta](https://github.com/tylercamp/palcalc/releases/tag/v1.7.6-beta-1)

**Comment by Sat727** [comment]
Seems to still crash with this version:
[CRASHLOG.zip](https://github.com/user-attachments/files/17529453/CRASHLOG.zip)

**Comment by tylercamp** [comment]
@Sat727 I saw you responded with continued errors but removed the comment? Are you still testing with the new version? I was unable to reproduce the crash from the CRASHLOG you sent in the deleted comment

**Comment by Sat727** [comment]
My mistake I was using the older version. It seems to work. It shows older players who were not appearing in the filter as well as being able to inspect the save when previously impossible. However one player seems to appear as "unknown" but this was the previously hidden player so it is visible currently.

**Comment by tylercamp** [comment]
Released in [v1.7.6](https://github.com/tylercamp/palcalc/releases/tag/v1.7.6)
